### ISSUE TITLE
The ModalFooterTagHelper lacks await in ProcessAsync implementation

### ISSUE THREAD

**Issue by peterblazejewicz** [dpaquette/TagHelperSamples#11]
https://github.com/dpaquette/TagHelperSamples/blob/master/TagHelperSamples/src/TagHelperSamples.Bootstrap/ModalFooterTagHelper.cs#L24-L38

```
TagHelperSamples/TagHelperSamples/src/TagHelperSamples.Bootstrap/
ModalFooterTagHelper.cs(24,36): 
DNXCore,Version=v5.0 warning CS1998: 
This async method lacks 'await' operators and will run synchronously. 
Consider using the 'await' operator to await non-blocking API calls, 
or 'await Task.Run(...)' to do CPU-bound work on a background thread.
```

Most probably that could be changed to use just sync version as in `toggle` implementation:
https://github.com/dpaquette/TagHelperSamples/blob/master/TagHelperSamples/src/TagHelperSamples.Bootstrap/ModalToggleTagHelper.cs#L20-L24
Thanks!

**Comment by dpaquette** [comment]
Fixed
