### ISSUE TITLE
Markdown helper should not use p tag wrapper

### ISSUE THREAD

**Issue by dotnetchris** [dpaquette/TagHelperSamples#19]
Markdown generates p tags, it doesn't make sense to force p tags inside of a wrapper p tag. The wrapper tag really should be div, article, section, or even span. (or even literal text and no tag at all, if that's an option for tag helpers)

**Comment by dpaquette** [comment]
Very good point! I will fix this tomorrow

**Comment by dotnetchris** [comment]
I feel like the greatest setup would be

``` html
<markdown>##MyHeader</markdown> 
```

would result in 

``` html
<h1>MyHeader</h1>
```

And

``` html
<article markdown>##MyHeader<article>
```

would result in

``` html
<article>
<h1>MyHeader</h1>
</article>
```

**Comment by dpaquette** [comment]
Hmm.. That might work. I will need to experiment a little.

**Comment by dpaquette** [comment]
Nice! Thanks @MaximRouiller
