### ISSUE TITLE
Use a Markdown library that supports .NET Core

### ISSUE THREAD

**Issue by dpaquette** [dpaquette/TagHelperSamples#20]
MarkdownSharp doesn't support .NET Core and also seems to be inactive.

**Comment by dpaquette** [comment]
https://github.com/Knagis/CommonMark.NET

**Comment by RickStrahl** [comment]
I've been using CommonMark in a few projects (full framework though) and it works well. I think they're still working on the Core.NET implementation but it's in the works.

**Comment by MaximRouiller** [comment]
It's in pull request.

**Comment by dpaquette** [comment]
Done! Thanks @MaximRouiller
