### ISSUE TITLE
Better bundling with asp.net mvc 6

### ISSUE THREAD

**Issue by SebastianStehle** [dpaquette/TagHelperSamples#4]
Hi, I have a solution for better bundling support. I use gulp include (https://www.npmjs.com/package/gulp-include) to define bundles which are built in the deployment process. For development I want to include the raw files without minification.

e.g wwwroot/scripts/main.bundle

```
 //= include /js/schemas/controllers.list.js
 //= include /js/app.js
```

to include this bundle files you can use the following code:

```
<environment names="Development">
    <script-bundle file="~/scripts/main.bundle"></script-bundle>
</environment>
<environment names="Staging,Production">
    <script-bundle file="~/scripts/main.bundle" bundle="true" minified="true"></script-bundle>
</environment>
```

You can find the source code here: https://gist.github.com/SebastianStehle/258998d761dad255228c

The advantage of this solution is, that there is only one place where to define the bundles. In contrast to this solution: http://www.jeffreyfritz.com/2015/05/where-did-my-asp-net-bundles-go-in-asp-net-5/

**Comment by dpaquette** [comment]
This is great! I like how you used gulp-inject. How would you feel about submitting a pull request so you get credit for the contribution? Take a look at our existing samples and let me know if you have any questions.

Also, I wonder if it would be possible to build this by extending the existing MVC Script tag helper and adding a bundle-definition-file attribute. I'm not sure if that is do-able but may be worth exploring.

**Comment by dpaquette** [comment]
Closing this because this will be handled by the Bundler Minifier https://github.com/madskristensen/BundlerMinifier
