### ISSUE TITLE
Update Nuget packages with RTM versions

### ISSUE THREAD

**Issue by dpaquette** [dpaquette/TagHelperSamples#40]

**Comment by peterorjeff** [comment]
I see from your "Updated to RTM" commit that a reference to `Microsoft.AspNetCore.Mvc.ViewFeatures;` was added in a couple of places.

I have just upgraded from RC2 to RTM and am receiving the following run-time error:

> Encountered an unexpected error when attempting to resolve tag helper directive '@addTagHelper' with value '_, TagHelperSamples.Markdown'. Error: Could not load type 'Microsoft.AspNetCore.Mvc.Rendering.ModelExpression' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> @addTagHelper "_, TagHelperSamples.Markdown"

#### Questions
1. Do you think the RTM version will resolve this?
2. Any ETA on the nuget packages?

**Comment by dpaquette** [comment]
1. I hope so.
2. Hopefully tonight

**Comment by peterorjeff** [comment]
Awesome, thanks for the quick turnaround!

**Comment by dpaquette** [comment]
Nuget packages updated to v1.1.1. Tested with new Asp.NET Core RTM app and all work as expected.

**Comment by peterorjeff** [comment]
v1.1.1 has resolved my issue, thanks again!

**Comment by dpaquette** [comment]
Glad to hear it works for you
