### ISSUE TITLE
NavLinkTagHelper doesn't output A inside LI

### ISSUE THREAD

**Issue by superware** [dpaquette/TagHelperSamples#41]
In RTM, NavLinkTagHelper doesn't output A inside LI, so for:

`<nav-link asp-controller="Home" asp-action="About">About</nav-link>`

I'm actually getting:

`<li class="active">About</li>`

Any idea? thanks!

**Comment by dpaquette** [comment]
well that's unexpected. I will take a look

**Comment by superware** [comment]
hi, have you managed to reproduce?

**Comment by dpaquette** [comment]
Sorry, I haven't had time to look at this yet.

**Comment by thoemmi** [comment]
@dpaquette Have you a planned a new release including this fix?

**Comment by dpaquette** [comment]
Sorry, I have been busy with too many projects. I will try to get a new release out in the next few days.
