### ISSUE TITLE
Is there any tag helper to add prefix to img' src attribute?

### ISSUE THREAD

**Issue by xiaoxin01** [dpaquette/TagHelperSamples#51]
I want to do some thing like this:

```
<img src="a.jpg" asp-append-cdn=true />
```

render as:

```
<img src="http://somecdn/a.jpg" />
```

Is there any way to do this?

**Comment by peterblazejewicz** [comment]
The built-in ImageTagHelper should be exended:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/ImageTagHelper.cs
It supports asp-append-version already.

**Comment by xiaoxin01** [comment]
@peterblazejewicz 

Got it, Thanks:)
