### ISSUE TITLE
Any plans to merge #43?

### ISSUE THREAD

**Issue by Tyf0x** [dpaquette/TagHelperSamples#60]
Having the ability to discriminate against action parameters would allow to have menus targeting the same controller and action, but with different parameters.

More info: http://www.patrickniezen.com/2016/10/2/marking-html-elements-active-based-on-the-current-route-using-asp-net-mvc-tag-helpers

note: I'm note the author of the article or PR #43

**Comment by dpaquette** [comment]
Done
