### ISSUE TITLE
Implement tag helper for resource based authorization

### ISSUE THREAD

**Issue by dpaquette** [dpaquette/TagHelperSamples#66]
The main scenario I'm picturing here is the ability to render or supress rendering of an edit button based on the results of resource authorization

**Comment by nj-sketch** [comment]
I was thinking of it too. Currently, what we do is send user permission for the resource (Create, Update, Delete) in our views and use their value in javascript and work accordingly. We use mostly datatables. Its a bit messy and have been looking for right way.

**Comment by dpaquette** [comment]
Done in PR #68 .

For more details see https://davepaquette.com/archive/2017/11/28/authorize-resource-tag-helper.aspx
