### ISSUE TITLE
Authorise TagHelper in For Loop

### ISSUE THREAD

**Issue by jigarce** [dpaquette/TagHelperSamples#74]
Hi,

Nice article, Very easy to use.

Just one question , while using this resource based Tag helper in for loop , it will check 10 time for Delete operation in database right ?

Single condition of Delete in for loop it will check 10 times in loop.

Do you have any simplified solution to that?

Regards,
jigar

**Comment by dpaquette** [comment]
If it is a resource based policy and that policy handler does a database check, then I don't see a way around it. If you have 10 items to check, it will require 10 calls to the database.
