### ISSUE TITLE
Authorize taghelper issue

### ISSUE THREAD

**Issue by dotnetshadow** [dpaquette/TagHelperSamples#77]
Hi there,

I tried to upgrade my asp.net core 2.2 app to asp.net core 3.0 preview 7 but I noticed I get the following error when using asp-authorize attribute

`Reference to type 'IAuthorizeData' claims it is defined in 'Microsoft.AspNetCore.Authorization', but it could not be found`

**Comment by dpaquette** [comment]
I have not looked at upgrading the authorize taghelper to ASP.NET Core 3.0 yet.  I will do that shortly after the official release of 3.0

**Comment by fingers10** [comment]
@dpaquette any updates on this?

**Comment by msavarian** [comment]
> 
> 
> I have not looked at upgrading the authorize taghelper to ASP.NET Core 3.0 yet. I will do that shortly after the official release of 3.0

Dear David, pls do that (upgrade to version 3.0).
thanks

**Comment by dpaquette** [comment]
I will do my best to get this done this week. Sorry for the delay

**Comment by dpaquette** [comment]
@msavarian @fingers10 @dotnetshadow  I've published an update to https://www.nuget.org/packages/TagHelperSamples.Authorization/. Sadly I've run out of time to complete a full test tonight. I will test tomorrow but if any of you have a chance to give this a try please let me know if it works for you.  

Thanks all!

**Comment by dpaquette** [comment]
Fixed in #79

**Comment by dpaquette** [comment]
Confirmed fixed
